/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package welma.carpark.v2;

import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author ASUS
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
       
        //login userame1 = new login();
        //String user = 
        
        
        /*
        
        String user = new login().getUsername();
        String welcome = "Welcome " + user;
        txtuser.setText(welcome);
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdate = new org.jdesktop.swingx.JXDatePicker();
        txtbill = new javax.swing.JLabel();
        txthr = new java.awt.TextField();
        jcin = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtvno = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtuser.setText("Welcome user");
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duration (Hrs)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check-in");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, -1));

        txtbill.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 130));
        getContentPane().add(txthr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, -1));
        getContentPane().add(jcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Book");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 100, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicle Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));
        getContentPane().add(txtvno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\NB\\Richmun\\Welma carpark v2\\src\\welma\\carpark\\v2\\img\\bg2.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Random rand - new Random();R
        int val = (int)(Math.random() * 50 +1);
        int refid = 876547901 + val;
        String veh_no = txtvno.getText();
        String date = jdate.getDate().toString();
        String checkin = jcin.getFormatedTime().toString();
        String duration = txthr.getText();
        
        int hours = Integer.parseInt(duration);
        int payment = hours * 100;
        String paymt = Integer.toString(payment);
        String ref = Integer.toString(refid);
              
        if(veh_no.equals("") || date.equals("" )|| checkin.equals("")|| duration.equals("")){
        
            JOptionPane.showMessageDialog(null,"Please fill out relavant fields!");
           } 
        else {       
       
        
        JOptionPane.showMessageDialog(null,"Booking Confirmed! /nYour Vehicle No: " + veh_no + 
                     "\n" + "Booked for " + date + " from " + checkin + " for " +
                     duration + "hours. \n" + "Your reference No: " + ref +  "\n" + 
                     "You will pay " + paymt + "LKR upon checking out.");
        
       
        
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private lu.tudor.santec.jtimechooser.JTimeChooser jcin;
    private org.jdesktop.swingx.JXDatePicker jdate;
    private javax.swing.JLabel txtbill;
    private java.awt.TextField txthr;
    private javax.swing.JLabel txtuser;
    private java.awt.TextField txtvno;
    // End of variables declaration//GEN-END:variables
}
